import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { generationSignal } from '../src/generated-code.ts';

/**
 * The check that keeps build output out of the graph.
 *
 * Two of the three repositories where the retry rules fired across a thirty six repository sweep matched
 * inside bundler output, and the components they raised were minifier symbols. A minified bundle is the
 * worst possible input to a pattern matcher: it concentrates a whole dependency tree into one file, so
 * every shape any rule looks for is in there somewhere, attached to a name that identifies nothing.
 *
 * The tests that matter most here are the ones in the other direction. Setting a file aside removes a
 * person's system from their own audit, so ordinary source has to survive every signal, including source
 * that is dense, source with long lines in it, and source that talks about generated code.
 */

/** A bundle in the shape the sweep found: one long line, names from a minifier's alphabet. */
const minifiedBundle = (): string => {
  const body = Array.from(
    { length: 40 },
    (_unused, index) =>
      `function ${String.fromCharCode(97 + (index % 26))}${index}(e,t,n){var r=e[t];try{for(var i=0;i<n;i++){r=r(i)}}catch(o){return o}return r}`,
  ).join('');
  return `!function(e,t){"use strict";${body}}(window,document);\n`;
};

const handWritten = (): string =>
  [
    'import { readFileSync } from "node:fs";',
    '',
    'export const loadConfiguration = (path: string): Configuration => {',
    '  const contents = readFileSync(path, "utf8");',
    '  for (const attempt of [1, 2, 3]) {',
    '    try {',
    '      return parseConfiguration(contents);',
    '    } catch (error) {',
    '      if (attempt === 3) throw error;',
    '    }',
    '  }',
    '  throw new Error("unreachable");',
    '};',
    '',
  ]
    .join('\n')
    .padEnd(600, ' ');

describe('code a program wrote', () => {
  it('recognises a minified bundle from its shape alone, wherever it sits', () => {
    assert.equal(generationSignal(minifiedBundle(), 'javascript'), 'minified');
  });

  it('recognises build output from the source map reference it ends with', () => {
    const compiled = `${handWritten()}\n//# sourceMappingURL=index.js.map\n`;
    assert.equal(generationSignal(compiled, 'javascript'), 'source_map');
  });

  it('recognises a file whose own header says a program wrote it', () => {
    const emitted = ['# Generated by the protocol buffer compiler. DO NOT EDIT!', 'x = 1', ''].join(
      '\n',
    );
    assert.equal(generationSignal(emitted, 'python'), 'declared');
  });
});

describe('code a person wrote', () => {
  it('survives, including the retry shape the rules look for', () => {
    assert.equal(generationSignal(handWritten(), 'typescript'), undefined);
  });

  it('survives one enormous encoded line, which is long without being minified', () => {
    const embedded = `export const icon = "data:image/png;base64,${'A'.repeat(4000)}";\n`;
    assert.equal(generationSignal(embedded, 'typescript'), undefined);
  });

  it('survives dense short names, which are short without being packed', () => {
    const dense = Array.from({ length: 60 }, (_unused, i) => `  const v${i} = a * b + c;`).join(
      '\n',
    );
    assert.equal(generationSignal(dense, 'typescript'), undefined);
  });

  /*
   * From the corpus, and the reason both signals are measured on the code rather than on the file. This is
   * one hand written React function around a drawing instruction, and the single letter path commands
   * inside that attribute made sixty one percent of its apparent identifiers two characters or shorter on
   * lines averaging a hundred and thirty three characters. Both signals fired on a person's source.
   */
  it('survives an icon component whose drawing data is longer than its code', () => {
    const path = Array.from(
      { length: 120 },
      (_unused, i) => `M${i} ${i}a4 4 0 0 0-4 4c0 .277.005.55.01.805v${i}h-2z`,
    ).join('');
    const icon = [
      "import * as React from 'react';",
      '',
      'const FunctionsIcon = (props: React.SVGProps<SVGSVGElement>) => (',
      "  <svg xmlns='http://www.w3.org/2000/svg' fill='currentColor' {...props} viewBox='0 0 24 24'>",
      `    <path fillRule='evenodd' clipRule='evenodd' d='${path}' />`,
      '  </svg>',
      ');',
      '',
      'export default FunctionsIcon;',
      '',
    ].join('\n');
    assert.equal(generationSignal(icon, 'typescript'), undefined);
  });

  /*
   * The words a generator writes are also words a person writes about generators. Anchoring the header
   * markers to comment lines is what keeps this module, and any module that discusses the convention,
   * out of its own net.
   */
  it('survives mentioning the markers outside a header comment', () => {
    const discussion = [
      'export const MARKERS = ["@generated", "do not edit"];',
      'export const isGeneratedHeader = (line: string): boolean =>',
      '  MARKERS.some((marker) => line.includes(marker));',
      '',
    ].join('\n');
    assert.equal(generationSignal(discussion, 'typescript'), undefined);
  });

  /*
   * A configuration document is read for what it declares rather than analysed for shapes, and a minified
   * one is still the declaration. Refusing it would remove a repository's description of itself.
   */
  it('never sets aside a configuration document, however it is formatted', () => {
    assert.equal(generationSignal(minifiedBundle(), 'json'), undefined);
    assert.equal(generationSignal(minifiedBundle(), 'yaml'), undefined);
  });

  it('says nothing about a file too small for its shape to mean anything', () => {
    assert.equal(generationSignal('const a=1,b=2,c=a+b;\n', 'javascript'), undefined);
  });
});
